### ISSUE TITLE
Go To Symbol Feature

### ISSUE THREAD

**Issue by andriisalamatin** [ilich/vscode-coldfusion#19] opened 2017-08-10 12:24 UTC
Is it possible to integrate "Go To Symbol" VS Code feature (Ctrl + Shift + O)? It is Ctrl + R in Sublime plugin.

**Comment by ilich** [comment] 2017-08-11 12:29
Thank you for the proposal. I am going to start working on the extension at the end of September.

**Comment by KamasamaK** [comment] 2017-08-15 19:27
This is a duplicate of Issue #11

**Closed as completed** 2017-09-07 13:28 UTC
Labels: duplicate
